### ISSUE TITLE
Stopping the nvidia-vgpu-mgr service fails

### ISSUE THREAD

**Issue by starcraft66** [danielfullmer/nixos-nvidia-vgpu#3]
The ExecStopPost phase fails because the `-r` argument to `rm` is missing at https://github.com/danielfullmer/nixos-nvidia-vgpu/blob/master/default.nix#L123 which causes this error:
```
Apr 23 12:58:25 luna rm[2131770]: /nix/store/485sqh570qixsv9wk0d59vrvs35pqja0-coreutils-8.32/bin/rm: cannot remove '/var/run/nvidia-vgpu-mgr': Is a directory
```

**Comment by danielfullmer** [comment]
Thanks again!
